### ISSUE TITLE
Erro user.getLogin()

### ISSUE THREAD

**Issue by JEZIGA01** [Fernanda-Kipper/auth-api#2]
na classe auth/security/infra/TokenService.java   aparece que nao tenho o método getLogin, o que seria esse problema ?

```java
public String generateToken(User user){
        try{
            Algorithm algorithm = Algorithm.HMAC256(secret);
            String token = JWT.create()
                    .withIssuer("auth-api")
                    .withSubject(user.getLogin())
                    .withExpiresAt(genExpirationDate())
                    .sign(algorithm);
            return token;
        } catch (JWTCreationException exception) {
            throw new RuntimeException("Error while generating token", exception);
        }
    }
 ```

**Comment by Fernanda-Kipper** [comment]
O método getLogin vem do nosso `User` esse `User` tem as seguintes propriedades: um `login`, `password`, `id`e um `type`... e o método getLogin é gerado automáticamente pelo lombok ao usarmos a anotação `@Getter` em cima da nossa classe, olha:


```java
@Table(name = "users")
@Entity(name = "users")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "id")
public class User implements UserDetails {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;
    private String login;
    private String password;
    private UserRole role;
```

Talvez **se você mudou as propriedades da classe User**, exemplo mudou de `login` para chamar de `email` **esse pode ser o erro**, ai você precisaria fazer` user.getEmail()` ao invés de `user.getLogin()` como mostrei no vídeo :)
